#cloud-config

hostname: coreos01

coreos:  
  etcd:    
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start


users:
  - name: lintong
    passwd: $6$rounds=4096$U.09rxYXynk3hsq$z9c0IY3ittszzKH8NE9ODd97t3pMZ5CM6Wol8y3VHIjGvxgDKBobU9wmegPxhVYGlFByZpe0A1BzucDpM8rsF.
    groups:
      - sudo
      - docker
