#cloud-config

hostname:  coreos01

coreos:  
  etcd:    
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start


users:
  - name: lintong
    coreos-ssh-import-github: lintong
  
  - groups:
    - sudo
    - docker
